<?php

namespace Msi\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageCategoryRepository extends EntityRepository
{
}