<?php

namespace Msi\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
  public function findWithFilters(array $filters = array())
  {
    $q = $this->createQueryBuilder('a');
    
    foreach ($filters as $key => $value) {
      if ($value != -1) {
        $q->andWhere('a.'.$key.' = :'.$key)
          ->setParameter($key, $value);
      }
    }
    
    $q->orderBy('a.title', 'ASC');
    
    return $q->getQuery();
  }
  
  public function findPage($slug = null)
  {
    $q = $this->createQueryBuilder('a')
      ->where('a.published = 1');
    if ($slug) {
      $q->andWhere('a.slug = ?1')
        ->setParameter(1, $slug);
    } else {
      $q->andWhere('a.home = 1');
    }
      
    return $q->getQuery()->getSingleResult();
  }
}