<?php

namespace Msi\ContentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageCategoryRepository extends EntityRepository
{
  public function findWithFilters(array $filters = array())
  {
    $q = $this->createQueryBuilder('a');
    
    foreach ($filters as $key => $value) {
      if ($value != -1) {
        $q->andWhere('a.'.$key.' = :'.$key)
          ->setParameter($key, $value);
      }
    }
    
    $q->orderBy('a.name', 'ASC');
    
    return $q->getQuery();
  }
}