page:
  pattern:  /
  defaults: { _controller: MsiContentBundle:admin\Page:index }

page_batch:
  pattern:  /batch/
  defaults: { _controller: MsiContentBundle:admin\Page:batch }

page_filter:
  pattern:  /filter
  defaults: { _controller: MsiContentBundle:admin\Page:setFilters }

page_limit:
  pattern:  /limit
  defaults: { _controller: MsiContentBundle:admin\Page:setLimit }

page_new:
  pattern:  /new/
  defaults: { _controller: MsiContentBundle:admin\Page:new }

page_create:
  pattern:  /create/
  defaults: { _controller: MsiContentBundle:admin\Page:create }
    
page_edit:
  pattern:  /{id}/edit/
  defaults: { _controller: MsiContentBundle:admin\Page:edit }
  requirements:
    id: \d+

page_update:
  pattern:  /{id}/update/
  defaults: { _controller: MsiContentBundle:admin\Page:update }
  requirements:
    id: \d+

page_reset_filters:
  pattern:  /filter/reset
  defaults: { _controller: MsiContentBundle:admin\Page:resetFilters }